# Copyright (C) Microarray
# MicroArray Fprint Driver Code
# MAKEFILE
# Date: 2017-3-15
# Version: v4.0.06 
# Author: guq
# Contact: guq@microarray.com.cn

## add by microarray start
obj-y += madev.o qualcomm-settings.o
## add by microarray end
