## //lihaiyan@wind-mobi.com 20171030 +++

obj-$(CONFIG_DTV_FC8350_SUPPORT) = bbm.o fc8350.o fc8350_bb.o fc8350_i2c.o fc8350_isr.o fc8350_spi.o fc8350_tun.o fc8350_tun_table.o fci_hal.o fci_hpi.o fci_oal.o fci_ringbuffer.o fci_tun.o

## //lihaiyan@wind-mobi.com 20171030 ---