#
# Makefile - Intel MIC Linux driver.
# Copyright(c) 2013, Intel Corporation.
#
## /* add by lihaiyan start  */
obj-$(CONFIG_LEADCORE_FINGERPRINT) += leadcore/
obj-$(CONFIG_MICROARRAY_FINGERPRINT) += microarray/
obj-$(CONFIG_SUNWAVE_FINGERPRINT) += sunwave/
## /* add by lihaiyan end  */
